apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapi
spec:
  selector:
    matchLabels:
      app: serverapi
  template:
    metadata:
      labels:
        app: serverapi
    spec:
      containers:
      - name: serverapi
        image: server:k8s
        resources:
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: serverapi
spec:
  type: NodePort
  selector:
    app: serverapi
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30801
