apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
spec:
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: index:k8s
        imagePullPolicy: IfNotPresent
        resources:
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: index
spec:
  type: NodePort
  selector:
    app: index
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30800