apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapi
spec:
  selector:
    matchLabels:
      app: loginapi
  template:
    metadata:
      labels:
        app: loginapi
    spec:
      containers:
      - name: loginapi
        image: login:k8s
        resources:
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: loginapi
spec:
  selector:
    app: loginapi
  ports:
  - port: 8082
    targetPort: 8082
    

