apiVersion: v1
kind: Secret
metadata:
  name: pma-secret
type: Opaque
data:
  PMA_HOST: bXlzcWw=
  PMA_PORT: MzMwNg==
  PMA_USER: cm9vdA==
  PMA_PASSWORD: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: myapp
        image: phpmyadmin:latest
        imagePullPolicy: IfNotPresent
        resources:
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: pma-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: NodePort
  selector:
    app: pma
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30900