apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
spec:
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: todo:k8s
        resources:
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: todolist
spec:
  selector:
    app: todolist
  ports:
  - port: 8083
    targetPort: 8083
